# Generated by Django 5.2 on 2025-04-18 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(help_text='ایپی یا شماره تلفن', max_length=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='زمان ایجاد شدن')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(help_text='ایپی یا شماره تلفن', max_length=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='زمان ایجاد شدن')),
                ('type', models.CharField(choices=[('0', 'login'), ('1', 'verifyCode')], help_text='نوع درخواست', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام', max_length=255, null=True)),
                ('lastName', models.CharField(help_text='نام خانوادگی', max_length=255, null=True)),
                ('email', models.EmailField(help_text='ایمیل', max_length=255, null=True, unique=True)),
                ('password', models.CharField(help_text='رمز', max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('phoneNumber', models.CharField(help_text='شماره تلفن', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+98?)?{?(0?9[0-9]{9,9}}?)$')])),
                ('modifiedAt', models.DateTimeField(auto_now=True, help_text='زمان اصلاح شدن')),
                ('status', models.PositiveSmallIntegerField(default=0, help_text='وضعیت')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='زمان ایجاد شدن')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کد تایید', max_length=5)),
                ('phoneNumber', models.CharField(help_text='شماره تلفن', max_length=17)),
                ('isUsed', models.PositiveSmallIntegerField(default=0, help_text='استفاده شده')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='زمان ایجاد شدن')),
            ],
        ),
    ]
