# Generated by Django 5.2 on 2025-04-18 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(help_text='شماره تلفن', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+98?)?{?(0?9[0-9]{9,9}}?)$')]),
        ),
    ]
