# Generated by Django 5.2 on 2025-04-19 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='ban',
            name='bannedUntil',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 15, 29, 15, 628662, tzinfo=datetime.timezone.utc), help_text='زمان پایان بن'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='string',
            field=models.CharField(help_text='ایپی یا شماره تلفن', max_length=255),
        ),
    ]
