# Generated by Django 5.2 on 2025-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_ban_createdat_ban_banneduntil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='bannedUntil',
            field=models.DateTimeField(help_text='زمان پایان بن'),
        ),
    ]
